### PR TITLE
Slide image alt & title attributes

### PR DESCRIPTION
**Pull request by richardadamdean**
Hi Really Simple,

Really like your plugin, it's a lovely piece of work :). I'm going to use it on an upcoming piece of functionality and my business really wanted each of the images in the slides to have alt and title attributes. If you're interested i've added some logic to do that and added a test case to prove it (which was a bit fiddly with the timings!). Feel free to add it in if you think it's of any use and thanks again for the awesome plugin! (Note I didn't regenerate the min version, what are you using to do this?).

Cheers

Richard

PS Our use of the plugin won't be out in the wild for a few weeks yet, but i'll let you know when it's out there so you can see it being used in anger!

### CODE REVIEW

**Comment by andygott** [comment]
Hi Richard,

Thanks for that—great work! Your additions have now been incorporated, and the change logs in both the README and on the docs and demos page have been updated accordingly.

Do you have an online presence that we can link to when we credit your contribution?

Looking forward to seeing how your use RS Slideshow.

Thanks again,

Andy

**Comment by andygott** [comment]
I didn't answer your question about minification. For quick minification of a single script like this, I tend to use: http://fmarcia.info/jsmin/test.html

Andy

**Comment by richardadamdean** [comment]
Hey Andy,

Sorry not to get back to you earlier, but thanks for such a quick turnaround on the pull request! If you want to can link to my (fairly dormant) blog at blog.richardadamdean.com or my (fairly dormant) twitter account @rdean (it might encourage me to start using one of them again!). We're now working through a pile of stories to include the slideshow in various guises across a lot of different sites (there'll probably be several hundred slideshows in use one we're fully up to speed!). As soon as they start being published i'll drop you a line so you can take a look.

Cheers

Richard

**Comment by andygott** [comment]
Hi Richard,

It's great to hear that RS Slideshow is getting some heavy use – I'll look forward to seeing your project in-the-wild.

I've linked to your Twitter account from the change log at the bottom of our RS Slideshow page:
http://reallysimpleworks.com/slideshow/#change-log

Thanks again for the contribution.

Andy

**Pull request merged**
